/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject3;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        Menu = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rice = new javax.swing.JComboBox<>();
        food = new javax.swing.JComboBox<>();
        drink = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        add1 = new javax.swing.JComboBox<>();
        add2 = new javax.swing.JComboBox<>();
        add3 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Result = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        LOW = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        out = new javax.swing.JScrollPane();
        ot = new javax.swing.JTextPane();
        total = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        totalrice = new javax.swing.JTextField();
        totalfood = new javax.swing.JTextField();
        totaldrink = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("From");
        getContentPane().setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(255, 153, 153));

        login.setFont(new java.awt.Font("BrowalliaUPC", 1, 24)); // NOI18N
        login.setText("เลือก Menu");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("BrowalliaUPC", 1, 36)); // NOI18N
        jLabel1.setText("ชื่อ");

        jLabel2.setFont(new java.awt.Font("BrowalliaUPC", 1, 36)); // NOI18N
        jLabel2.setText("เบอร์โทร");

        jLabel3.setFont(new java.awt.Font("BrowalliaUPC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("หนีโควิดมาสั่งข้าว");

        name.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N

        tel.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("BrowalliaUPC", 1, 36)); // NOI18N
        jLabel8.setText("ที่อยู่");

        add.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tel)
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Login, "card2");

        Menu.setBackground(new java.awt.Color(204, 204, 0));

        menu.setFont(new java.awt.Font("BrowalliaUPC", 1, 36)); // NOI18N
        menu.setText("ยืนยัน");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("BrowalliaUPC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 102));
        jLabel4.setText("อาหารตามสั่ง");

        jLabel5.setFont(new java.awt.Font("BrowalliaUPC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("ก๋วยเตี๋ยว");

        jLabel6.setFont(new java.awt.Font("BrowalliaUPC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("เครื่องดื่ม");

        rice.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        rice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "กะเพราหมูสับ", "คะน้าหมูกรอบ", "ผัดพริกแกง", "กะเพราไก่", "กะเพราหมูกรอบ" }));

        food.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        food.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "เส้นเล็กหมู", "เส้นหมี่หมู", "เส้นใหญ่หมู", "บะหมี่หมูแดง", "สุกี้หมู", "สุกี้แห้ง", " " }));

        drink.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        drink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "น้ำอัดลม", "น้ำเปล่า", "น้ำเก๊กฮวย", "น้ำกระเจี๊ยบ" }));

        jLabel7.setFont(new java.awt.Font("JasmineUPC", 1, 56)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("หนีโควิดมาสั่งข้าว");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("กะเพราหมูสับ ราคา 40 บาท");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ผัดพริกแกง ราคา 40 บาท");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("คะน้าหมูกรอบ ราคา 50 บาท");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("กะเพราไก่ ราคา 40 บาท");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("กะเพราหมูกรอบ ราคา 50 บาท");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("ราคาข้าวตามสั่ง");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("ราคาก๋วยเตี๋ยว");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("เส้นเล็กหมู ราคา 40 บาท");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("เส้นหมี่หมู ราคา 40 บาท");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("เส้นใหญ่หมู ราคา 40 บาท");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("บะหมี่หมูแดง ราคา 40 บาท");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("สุกี้หมู ราคา 40 บาท");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("สุกี้แห้ง ราคา 40 บาท");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("ราคาเครื่องดื่ม");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("น้ำอัดลม ราคา 20 บาท");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("น้ำเปล่า ราคา 10 บาท");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("น้ำเก๊กฮวย ราคา 30 บาท");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("น้ำกระเจี๊ยบ ราคา 30 บาท");

        add1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3" }));

        add2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3" }));

        add3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3" }));

        jLabel33.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 0, 102));
        jLabel33.setText("จำนวน");

        jLabel34.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        jLabel34.setText("จำนวน");

        jLabel35.setFont(new java.awt.Font("BrowalliaUPC", 1, 18)); // NOI18N
        jLabel35.setText("จำนวน");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rice, 0, 203, Short.MAX_VALUE)
                            .addComponent(food, 0, 203, Short.MAX_VALUE)
                            .addComponent(drink, 0, 203, Short.MAX_VALUE)
                            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drink, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addComponent(menu))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(33, 33, 33)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(92, 92, 92)))
                .addGap(22, 22, 22))
        );

        getContentPane().add(Menu, "card3");

        Result.setBackground(new java.awt.Color(255, 102, 0));

        jLabel36.setFont(new java.awt.Font("IrisUPC", 0, 36)); // NOI18N
        jLabel36.setText("รายการที่คุณ");

        LOW.setFont(new java.awt.Font("IrisUPC", 0, 36)); // NOI18N

        jLabel38.setFont(new java.awt.Font("IrisUPC", 0, 36)); // NOI18N
        jLabel38.setText(" ได้สั่งไว้");

        ot.setFont(new java.awt.Font("BrowalliaUPC", 0, 18)); // NOI18N
        out.setViewportView(ot);

        jLabel37.setFont(new java.awt.Font("AngsanaUPC", 1, 24)); // NOI18N
        jLabel37.setText("ราคารวมทั้งหมด");

        javax.swing.GroupLayout ResultLayout = new javax.swing.GroupLayout(Result);
        Result.setLayout(ResultLayout);
        ResultLayout.setHorizontalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(out, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ResultLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(LOW, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultLayout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(totalrice)
                            .addComponent(totalfood)
                            .addComponent(totaldrink))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        ResultLayout.setVerticalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(LOW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalfood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totaldrink, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(Result, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        Login.setVisible(false);
        Menu.setVisible(true);
        Result.setVisible(false);
        
        this.setTitle("login");
    }//GEN-LAST:event_loginMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        Login.setVisible(false);
        Menu.setVisible(false);
        Result.setVisible(true);
        
        String NAME,RICE,FOOD,DRINK,ADD1,ADD2,ADD3;
        int Result,Result2,Result3;
        
        NAME = name.getText();
        LOW.setText(NAME);
        
        RICE = rice.getSelectedItem().toString();
        FOOD = food.getSelectedItem().toString();
        DRINK = drink.getSelectedItem().toString();
        
        ADD1 = add1.getSelectedItem().toString();
        ADD2 = add2.getSelectedItem().toString();
        ADD3 = add3.getSelectedItem().toString();
        
        ot.setText(""+RICE+"\t\tจำนวน "+ADD1+" กล่อง\n"+FOOD+"\t\tจำนวน "+ADD2+" กล่อง\n"+DRINK+"\t\tจำนวน "+ADD3+" กล่อง");        
        this.setTitle("Menu");
        
        Food much = new Food();
        if(RICE == "กะเพราหมูสับ"){
            much.A = 40;
            Result = much.A;
            if(ADD1 == "-"){
                Result = 0;
            }
            else if(ADD1 == "1"){
                Result = much.A;
            }
            else if(ADD1 == "2"){
                Result = much.Rice1();
            }
            else if(ADD1 == "3"){
                Result = much.Rice7();      
            }totalrice.setText(""+Result);
        }else if(RICE == "คะน้าหมูกรอบ"){
            much.B = 50;
            Result = much.B;
            if(ADD1 == "-"){
                Result = 0;
            }
            else if(ADD1 == "1"){
                Result = much.B;
            }
            else if(ADD1 == "2"){
                Result = much.Rice2();
            }
            else if(ADD1 == "3"){
                Result = much.Rice8();      
            }totalrice.setText(""+Result);
        }else if(RICE == "ผัดพริกแกง"){
            much.C = 40;
            Result = much.C;
            if(ADD1 == "-"){
                Result = 0;
            }
            else if(ADD1 == "1"){
                Result = much.C;
            }
            else if(ADD1 == "2"){
                Result = much.Rice3();
            }
            else if(ADD1 == "3"){
                Result = much.Rice9();      
            }totalrice.setText(""+Result);
        }else if(RICE == "กะเพราไก่"){
            much.D = 40;
            Result = much.D;
            if(ADD1 == "-"){
                Result = 0;
            }
            else if(ADD1 == "1"){
                Result = much.D;
            }
            else if(ADD1 == "2"){
                Result = much.Rice4();
            }
            else if(ADD1 == "3"){
                Result = much.Rice10();      
            }totalrice.setText(""+Result);
        }else if(RICE == "กะเพราหมูกรอบ"){
            much.E = 50;
            Result = much.E;
            if(ADD1 == "-"){
                Result = 0;
            }
            else if(ADD1 == "1"){
                Result = much.E;
            }
            else if(ADD1 == "2"){
                Result = much.Rice5();
            }
            else if(ADD1 == "3"){
                Result = much.Rice11();      
            }totalrice.setText(""+Result);
        }
        Noodle MUCH = new Noodle();
        if(FOOD == "เส้นเล็กหมู"){
            MUCH.AA = 40;
            Result2 = MUCH.AA;
            if(ADD2 == "-"){
                Result2 = 0;
            }
            else if(ADD2 == "1"){
                Result2 = MUCH.AA;
            }
            else if(ADD2 == "2"){
                Result2 = MUCH.Nood1();
            }
            else if(ADD2 == "3"){
                Result2 = MUCH.Nood7();      
            }totalfood.setText(""+Result2);
        }else if(FOOD == "เส้นหมี่หมู"){
            MUCH.AA = 40;
            Result2 = MUCH.AA;
            if(ADD2 == "-"){
                Result2 = 0;
            }
            else if(ADD2 == "1"){
                Result2 = MUCH.AA;
            }
            else if(ADD2 == "2"){
                Result2 = MUCH.Nood1();
            }
            else if(ADD2 == "3"){
                Result2 = MUCH.Nood7();      
            }totalfood.setText(""+Result2);
        }else if(FOOD == "เส้นใหญ่หมู"){
            MUCH.AA = 40;
            Result2 = MUCH.AA;
            if(ADD2 == "-"){
                Result2 = 0;
            }
            else if(ADD2 == "1"){
                Result2 = MUCH.AA;
            }
            else if(ADD2 == "2"){
                Result2 = MUCH.Nood1();
            }
            else if(ADD2 == "3"){
                Result2 = MUCH.Nood7();      
            }totalfood.setText(""+Result2);
        }else if(FOOD == "บะหมี่หมูแดง"){
            MUCH.AA = 40;
            Result2 = MUCH.AA;
            if(ADD2 == "-"){
                Result2 = 0;
            }
            else if(ADD2 == "1"){
                Result2 = MUCH.AA;
            }
            else if(ADD2 == "2"){
                Result2 = MUCH.Nood1();
            }
            else if(ADD2 == "3"){
                Result2 = MUCH.Nood7();      
            }totalfood.setText(""+Result2);
        }else if(FOOD == "สุกี้หมู"){
            MUCH.AA = 40;
            Result2 = MUCH.AA;
            if(ADD2 == "-"){
                Result2 = 0;
            }
            else if(ADD2 == "1"){
                Result2 = MUCH.AA;
            }
            else if(ADD2 == "2"){
                Result2 = MUCH.Nood1();
            }
            else if(ADD2 == "3"){
                Result2 = MUCH.Nood7();      
            }totalfood.setText(""+Result2);
        }else if(FOOD == "สุกี้แห้ง"){
            MUCH.AA = 40;
            Result2 = MUCH.AA;
            if(ADD2 == "-"){
                Result2 = 0;
            }
            else if(ADD2 == "1"){
                Result2 = MUCH.AA;
            }
            else if(ADD2 == "2"){
                Result2 = MUCH.Nood1();
            }
            else if(ADD2 == "3"){
                Result2 = MUCH.Nood7();      
            }totalfood.setText(""+Result2);
        }
        Drink Drk = new Drink();
        if(DRINK == "น้ำอัดลม"){
            Drk.DRINK2 = 20;
            Result3 = Drk.DRINK2;
            if(ADD3 == "-"){
                Result3 = 0;
            }
            else if(ADD3 == "1"){
                Result3 = Drk.DRINK2;
            }
            else if(ADD3 == "2"){
                Result3 = Drk.DRINK222();
            }
            else if(ADD3 == "3"){
                Result3 = Drk.DRINK555();      
            }totaldrink.setText(""+Result3);
        }else if(DRINK == "น้ำเปล่า"){
            Drk.DRINK1 = 10;
            Result3 = Drk.DRINK1;
            if(ADD3 == "-"){
                Result3 = 0;
            }
            else if(ADD3 == "1"){
                Result3 = Drk.DRINK1;
            }
            else if(ADD3 == "2"){
                Result3 = Drk.DRINK111();
            }
            else if(ADD3 == "3"){
                Result3 = Drk.DRINK444();      
            }totaldrink.setText(""+Result3);
        }else if(DRINK == "น้ำเก๊กฮวย"){
            Drk.DRINK3 = 30;
            Result3 = Drk.DRINK3;
            if(ADD3 == "-"){
                Result3 = 0;
            }
            else if(ADD3 == "1"){
                Result3 = Drk.DRINK3;
            }
            else if(ADD3 == "2"){
                Result3 = Drk.DRINK333();
            }
            else if(ADD3 == "3"){
                Result3 = Drk.DRINK666();      
            }totaldrink.setText(""+Result3);
        }else if(DRINK == "น้ำกระเจี๊ยบ"){
            Drk.DRINK3 = 30;
            Result3 = Drk.DRINK3;
            if(ADD3 == "-"){
                Result3 = 0;
            }
            else if(ADD3 == "1"){
                Result3 = Drk.DRINK3;
            }
            else if(ADD3 == "2"){
                Result3 = Drk.DRINK333();
            }
            else if(ADD3 == "3"){
                Result3 = Drk.DRINK666();      
            }totaldrink.setText(""+Result3);
        }
        
        int Re = Integer.parseInt(totalrice.getText());
        int Re2 = Integer.parseInt(totalfood.getText());
        int Re3 = Integer.parseInt(totaldrink.getText());
        int TOTAL = Re + Re2 + Re3;
        total.setText(TOTAL+" บาท");
    }//GEN-LAST:event_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOW;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Result;
    private javax.swing.JTextField add;
    private javax.swing.JComboBox<String> add1;
    private javax.swing.JComboBox<String> add2;
    private javax.swing.JComboBox<String> add3;
    private javax.swing.JComboBox<String> drink;
    private javax.swing.JComboBox<String> food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login;
    private javax.swing.JButton menu;
    private javax.swing.JTextField name;
    private javax.swing.JTextPane ot;
    private javax.swing.JScrollPane out;
    private javax.swing.JComboBox<String> rice;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totaldrink;
    private javax.swing.JTextField totalfood;
    private javax.swing.JTextField totalrice;
    // End of variables declaration//GEN-END:variables

    private int Result() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private int Result2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
